# Generated by Django 5.0.6 on 2024-05-21 20:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_cover_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
