# Generated by Django 5.0.6 on 2024-05-22 08:31

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
