# Generated by Django 5.0.6 on 2024-06-02 21:00

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='915', max_length=11, unique=True, validators=[core.validators.validate_digit]),
            preserve_default=False,
        ),
    ]
