# Generated by Django 5.0.6 on 2024-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_activationviaemail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationviaemail',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
