# Generated by Django 5.0.6 on 2024-05-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_postcommentscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
