# Generated by Django 5.0.6 on 2024-06-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_goodpoint_weakpoint_productcomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'comment_of_product', 'verbose_name_plural': 'comments_of_products'},
        ),
    ]
