# Generated by Django 5.0.6 on 2024-06-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'brand'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productproperties',
            options={'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='subproductcategory',
            options={'verbose_name': 'sub_category', 'verbose_name_plural': 'sub_categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_date',
            new_name='datetime_updated',
        ),
    ]
