# Generated by Django 5.0.6 on 2024-06-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subsubproductcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproductcategory',
            name='parent',
        ),
    ]
