# Generated by Django 5.0.6 on 2024-06-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_subsubproductcategory_main_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subsubproductcategory'),
        ),
    ]
