# Generated by Django 5.0.6 on 2024-06-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_sub_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproductproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='products.product', verbose_name='محصول'),
        ),
    ]
