# Generated by Django 5.0.6 on 2024-06-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_setproductproperty_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
    ]
