# Generated by Django 5.0.6 on 2024-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code_of_color',
            field=models.CharField(blank=True, help_text='لطفا کد رنگ را بدون علامت # وارد کنید', max_length=100),
        ),
    ]
